export const CAMPS = [
  {
    id: 'camp-aluva',
    name: 'Aluva Town Hall Camp',
    location: 'Aluva, Ernakulam',
    district: 'Ernakulam',
    capacity: 400,
    occupied: 312,
    status: 'limited',
    distanceKm: 2.4,
    lat: 10.1076,
    lng: 76.3516,
    food: 'limited',
    water: 'available',
    medical: 'limited',
    contact: '0484-2628100',
    warden: 'Sunitha K.',
  },
  {
    id: 'camp-chalakudy',
    name: 'Chalakudy Parish Hall',
    location: 'Chalakudy, Thrissur',
    district: 'Thrissur',
    capacity: 220,
    occupied: 96,
    status: 'available',
    distanceKm: 18.1,
    lat: 10.3008,
    lng: 76.331,
    food: 'available',
    water: 'available',
    medical: 'limited',
    contact: '0480-2701122',
    warden: 'Fr. Jose Palayoor',
  },
  {
    id: 'camp-idukki',
    name: 'Idukki High School Camp',
    location: 'Painavu, Idukki',
    district: 'Idukki',
    capacity: 180,
    occupied: 174,
    status: 'unavailable',
    distanceKm: 64.0,
    lat: 9.849,
    lng: 76.976,
    food: 'unavailable',
    water: 'limited',
    medical: 'unavailable',
    contact: '0486-2233400',
    warden: 'Ramesh Nair',
  },
  {
    id: 'camp-kalpetta',
    name: 'Kalpetta Municipal Camp',
    location: 'Kalpetta, Wayanad',
    district: 'Wayanad',
    capacity: 300,
    occupied: 188,
    status: 'limited',
    distanceKm: 41.2,
    lat: 11.610,
    lng: 76.083,
    food: 'limited',
    water: 'available',
    medical: 'available',
    contact: '0493-6202211',
    warden: 'Fathima Beevi',
  },
  {
    id: 'camp-alappuzha',
    name: 'Alappuzha SDV Ground Camp',
    location: 'Alappuzha town',
    district: 'Alappuzha',
    capacity: 500,
    occupied: 210,
    status: 'available',
    distanceKm: 53.7,
    lat: 9.498,
    lng: 76.3388,
    food: 'available',
    water: 'available',
    medical: 'available',
    contact: '0477-2251515',
    warden: 'Anwar Hussain',
  },
  {
    id: 'camp-kozhikode',
    name: 'Kozhikode Beach Relief Camp',
    location: 'Kozhikode',
    district: 'Kozhikode',
    capacity: 260,
    occupied: 240,
    status: 'limited',
    distanceKm: 187,
    lat: 11.2588,
    lng: 75.7804,
    food: 'limited',
    water: 'limited',
    medical: 'available',
    contact: '0495-2361234',
    warden: 'Latha Menon',
  },
];

export function getCamp(id) {
  return CAMPS.find((camp) => camp.id === id) || CAMPS[0];
}
