export const REQUESTS = [
  {
    id: 'req-boat-kuttanad',
    title: 'Boat needed for 9 people',
    type: 'Rescue',
    priority: 'unavailable',
    status: 'unavailable',
    requester: 'Maya T., Kainakary',
    location: 'Kuttanad',
    requesterId: 'demo-citizen',
    acceptedVolunteerId: null,
    createdAt: '11 min ago',
    details: 'Family stranded on the first floor. Water at chest height on the lane.',
    timeline: [
      { id: 't1', title: 'Request opened', meta: '11 min ago', done: true, status: 'unavailable' },
      { id: 't2', title: 'Waiting for a boat crew', meta: 'Now', done: false },
      { id: 't3', title: 'Pickup and drop at camp', meta: 'Pending', done: false },
    ],
  },
  {
    id: 'req-insulin',
    title: 'Insulin for two patients',
    type: 'Medical',
    priority: 'limited',
    status: 'limited',
    requester: 'PHC Painavu',
    location: 'Idukki',
    requesterId: 'demo-citizen',
    acceptedVolunteerId: 'demo-medical_team',
    createdAt: '32 min ago',
    details: 'Cold-chain insulin. Can receive at the PHC gate.',
    timeline: [
      { id: 't1', title: 'Request opened', meta: '32 min ago', done: true, status: 'limited' },
      { id: 't2', title: 'Matched with IMA stock', meta: '10 min ago', done: true, status: 'available' },
      { id: 't3', title: 'On the road', meta: 'Pending', done: false },
    ],
  },
  {
    id: 'req-power',
    title: 'Electrician for pump set',
    type: 'Technical',
    priority: 'limited',
    status: 'limited',
    requester: 'Thrissur camp coordinator',
    location: 'Thrissur',
    requesterId: 'demo-citizen',
    acceptedVolunteerId: null,
    createdAt: '1 hr ago',
    details: 'Generator is running but the camp pump will not start.',
    timeline: [
      { id: 't1', title: 'Request opened', meta: '1 hr ago', done: true },
      { id: 't2', title: 'Volunteer assigned', meta: 'Pending', done: false },
    ],
  },
  {
    id: 'req-food',
    title: 'Evening meal for 80',
    type: 'Relief',
    priority: 'available',
    status: 'available',
    requester: 'Vadanapally Bhagavathy Temple dining hall',
    location: 'Vadanappally',
    requesterId: 'demo-citizen',
    acceptedVolunteerId: null,
    createdAt: '2 hr ago',
    details: 'Rice and sambar already cooking. Need vegetables and oil.',
    timeline: [
      { id: 't1', title: 'Request opened', meta: '2 hr ago', done: true, status: 'available' },
      { id: 't2', title: 'Accepted by SEEDS', meta: '1 hr ago', done: true, status: 'available' },
      { id: 't3', title: 'Delivered', meta: 'Pending', done: false },
    ],
  },
  {
    id: 'req-evacuation',
    title: 'Shift 14 elders from low-lying homes',
    type: 'Rescue',
    priority: 'unavailable',
    status: 'unavailable',
    requester: 'Ward member, Punnamada',
    location: 'Alappuzha',
    requesterId: 'demo-citizen',
    acceptedVolunteerId: null,
    createdAt: '3 hr ago',
    details: 'Need a high vehicle. Two people use wheelchairs.',
    timeline: [
      { id: 't1', title: 'Request opened', meta: '3 hr ago', done: true, status: 'unavailable' },
      { id: 't2', title: 'Crew accepted', meta: 'Pending', done: false },
    ],
  },
];

export function getRequest(id) {
  return REQUESTS.find((item) => item.id === id) || REQUESTS[0];
}
