export const RESOURCE_CATEGORIES = ['All', 'Food', 'Water', 'Shelter', 'Medical', 'Transport', 'Boats', 'Generator'];

export const RESOURCES = [
  {
    id: 'res-generator',
    name: 'Portable diesel generators',
    category: 'Generator',
    quantity: 4,
    unit: 'units',
    status: 'available',
    provider: 'Thrissur Electrical Guild',
    location: 'Thrissur',
    lat: 10.5276,
    lng: 76.2144,
    contact: '0487-2324411',
    notes: '5 kVA. Fuel for eight hours included. Pickup from the guild yard.',
  },
  {
    id: 'res-water-20l',
    name: 'Drinking water cans (20L)',
    category: 'Water',
    quantity: 80,
    unit: 'cans',
    status: 'available',
    provider: 'Kalamassery Rotary',
    location: 'Kalamassery',
    lat: 10.0520,
    lng: 76.3158,
    contact: '98470 11223',
    notes: 'Stacked at the warehouse gate. Pickup after 4pm.',
  },
  {
    id: 'res-rice-kits',
    name: 'Rice and grocery kits',
    category: 'Food',
    quantity: 140,
    unit: 'kits',
    status: 'limited',
    provider: 'SEEDS India',
    location: 'Thrissur',
    lat: 10.5276,
    lng: 76.2144,
    contact: '0487-2320099',
    notes: 'Each kit feeds a family of four for three days.',
  },
  {
    id: 'res-tarpaulin',
    name: 'Tarpaulin sheets',
    category: 'Shelter',
    quantity: 45,
    unit: 'sheets',
    status: 'limited',
    provider: 'Ponnani Fishermen Coop',
    location: 'Ponnani',
    lat: 10.7666,
    lng: 75.9257,
    contact: '98950 44112',
    notes: '12x18 ft. Good for temporary roofing.',
  },
  {
    id: 'res-ors',
    name: 'ORS and first-aid packs',
    category: 'Medical',
    quantity: 200,
    unit: 'packs',
    status: 'available',
    provider: 'IMA Ernakulam',
    location: 'Ernakulam',
    lat: 9.9816,
    lng: 76.2999,
    contact: '0484-2358001',
    notes: 'Includes gloves, gauze, and ORS sachets.',
  },
  {
    id: 'res-boats',
    name: 'Country boats with operators',
    category: 'Boats',
    quantity: 6,
    unit: 'boats',
    status: 'unavailable',
    provider: 'Kuttanad Boat Union',
    location: 'Kuttanad',
    lat: 9.4300,
    lng: 76.4200,
    contact: '97440 22881',
    notes: 'All six are already on rescue runs today.',
  },
  {
    id: 'res-tempo',
    name: 'Tempo travellers',
    category: 'Transport',
    quantity: 3,
    unit: 'vehicles',
    status: 'available',
    provider: 'Muvattupuzha Drivers Forum',
    location: 'Muvattupuzha',
    lat: 9.9769,
    lng: 76.5774,
    contact: '99470 66721',
    notes: 'Can move 12 people plus supplies.',
  },
  {
    id: 'res-blankets',
    name: 'Blankets and mats',
    category: 'Shelter',
    quantity: 320,
    unit: 'sets',
    status: 'available',
    provider: 'Alappuzha Relief Cell',
    location: 'Alappuzha',
    lat: 9.4981,
    lng: 76.3388,
    contact: '0477-2250900',
    notes: 'Stored dry. Ready for camp dispatch.',
  },
];

export function getResource(id) {
  return RESOURCES.find((item) => item.id === id) || RESOURCES[0];
}
